# Workflow based on https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {python-version: '3.6', doubleml-version: 'release'}
          - {python-version: '3.7', doubleml-version: 'release'}
          - {python-version: '3.8', doubleml-version: 'release'}
          - {python-version: '3.8', doubleml-version: 'dev'}
          - {python-version: '3.9', doubleml-version: 'release'}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.config.python-version }}
    - uses: actions/checkout@v3
      if: matrix.config.doubleml-version == 'dev'
      with:
        repository: DoubleML/doubleml-for-py
        path: doubleml-for-py
    - name: DoubleML dev version
      if: matrix.config.doubleml-version == 'dev'
      run: |
        cd doubleml-for-py
        pip install --editable .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest xgboost
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        pytest doubleml_serverless/
